"""initial migration

Revision ID: 25c2062d2821
Revises: 
Create Date: 2026-04-06 16:50:55.907484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c2062d2821'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('embeddings', sa.JSON(), nullable=True),
    sa.Column('encodings', sa.JSON(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('libraries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peptides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('embeddings', sa.JSON(), nullable=True),
    sa.Column('encodings', sa.JSON(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('library_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peptide_building_block',
    sa.Column('peptide_id', sa.String(length=36), nullable=False),
    sa.Column('building_block_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_block_id'], ['building_blocks.id'], ),
    sa.ForeignKeyConstraint(['peptide_id'], ['peptides.id'], ),
    sa.PrimaryKeyConstraint('peptide_id', 'building_block_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peptide_building_block')
    op.drop_table('peptides')
    op.drop_table('libraries')
    op.drop_table('building_blocks')
    # ### end Alembic commands ###
